[env:twatch-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@^1.4.0
    adafruit/Adafruit DRV2605 Library@^1.2.4
    bodmer/TFT_eSPI@^2.5.43
    lewisxhe/XPowersLib@^0.2.6
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    ; TFT_eSPI настройки для T-Watch-S3
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DINIT_SEQUENCE_3=1
    -DCGRAM_OFFSET=1
    -DTFT_RGB_ORDER=TFT_RGB
    -DTFT_INVERSION_ON=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=13
    -DTFT_SCLK=18
    -DTFT_CS=12
    -DTFT_DC=38
    -DTFT_RST=-1
    -DTFT_BL=45
    -DUSE_HSPI_PORT=1
    -DSPI_FREQUENCY=40000000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DSMOOTH_FONT=1
